name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug:Show first few lines of SSH key (masked)
        run: |
          echo "Showing first 3 lines of SSH key for debug:"
          echo "${{ secrets.EC2_SSH_KEY }}" | head -n 3
          echo "Showing last 2 lines of SSH key for debug:"
          echo "${{ secrets.EC2_SSH_KEY }}" | tail -n 2

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          key: ${{ secrets.EC2_SSH_KEY }}
          username: ec2-user
          host: 50.19.91.207
          script: |
            cd ~/backend-app
            git pull origin main
            npm install
            pm2 restart backend-app || pm2 start index.js --name backend-app
