name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH and PM2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 50.19.91.207
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/backend-app
            git pull origin main
            npm install
            pm2 restart backend-app || pm2 start index.js --name backend-app
